name: Create release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PRERELEASE: ${{ contains(inputs.tag, '-rc.') }}
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ inputs.tag }}
          generate_release_notes: true
          make_latest: ${{ env.PRERELEASE == 'false' }}
          draft: true
          prerelease: ${{ env.PRERELEASE == 'true' }}

      - name: Publish prerelease
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ inputs.tag }}
          draft: false
